#!/usr/bin/env bash
# This script displays numbers from 1 to 100 with FizzBuzz rules.

# Loop through numbers from 1 to 100
for num in {1..100}; do
  # Check if the number is a multiple of both 3 and 5
  if [[ $((num % 3)) -eq 0 && $((num % 5)) -eq 0 ]]; then
    echo "FizzBuzz"
  elif [[ $((num % 3)) -eq 0 ]]; then
    echo "Fizz"
  elif [[ $((num % 5)) -eq 0 ]]; then
    echo "Buzz"
  else
    echo "$num"
  fi
done
