#!/usr/bin/env bash
# This script reads the /etc/passwd file and outputs a story format for each user.

# Set Internal Field Separator (IFS) to ':'
IFS=':'

# Read the /etc/passwd file line-by-line using a while loop
while read -r USERNAME PASSWORD USER_ID GROUP_ID USER_ID_INFO HOME_DIRECTORY COMMAND; do
	  echo "The user $USERNAME is part of the $GROUP_ID gang, lives in $HOME_DIRECTORY and rides $COMMAND. $USER_ID's place is protected by the passcode $PASSWORD, more info about the user here: $USER_ID_INFO"
  done < /etc/passwd
