#!/usr/bin/env bash
# This script groups visitors by IP and HTTP status code and displays the data in a sorted list format

awk '{print $1, $9}' access.log | sort | uniq -c | sort -rn | awk '{print $1, $2, $3}'
